import {
  Baby,
  Backpack,
  Banknote,
  BookOpen,
  BookOpenCheck,
  BookMarked,
  Library,
  Bus,
  Building2,
  CalendarDays,
  Car,
  CarFront,
  ClipboardCheck,
  Clock,
  Compass,
  DoorOpen,
  Drum,
  Dumbbell,
  FlaskConical,
  Globe,
  GraduationCap,
  HandHeart,
  Heart,
  Landmark,
  Lightbulb,
  Mail,
  MapPin,
  Medal,
  Monitor,
  Moon,
  Music,
  NotebookPen,
  Palette,
  Pencil,
  Phone,
  Puzzle,
  Salad,
  School,
  Shield,
  ShieldCheck,
  Sparkles,
  Star,
  Sun,
  TreePine,
  Trophy,
  Users,
  Utensils,
  Waves,
  type LucideIcon,
} from "lucide-react";

const iconMap: Record<string, LucideIcon> = {
  baby: Baby,
  backpack: Backpack,
  banknote: Banknote,
  "book-open": BookOpen,
  "book-open-check": BookOpenCheck,
  "book-marked": BookMarked,
  library: Library,
  bus: Bus,
  "building-2": Building2,
  calendar: CalendarDays,
  car: Car,
  "car-front": CarFront,
  "clipboard-check": ClipboardCheck,
  clock: Clock,
  compass: Compass,
  "door-open": DoorOpen,
  drum: Drum,
  dumbbell: Dumbbell,
  "flask-conical": FlaskConical,
  globe: Globe,
  "graduation-cap": GraduationCap,
  "hand-heart": HandHeart,
  heart: Heart,
  landmark: Landmark,
  lightbulb: Lightbulb,
  mail: Mail,
  "map-pin": MapPin,
  medal: Medal,
  monitor: Monitor,
  moon: Moon,
  music: Music,
  "notebook-pen": NotebookPen,
  palette: Palette,
  pencil: Pencil,
  phone: Phone,
  puzzle: Puzzle,
  salad: Salad,
  school: School,
  shield: Shield,
  "shield-check": ShieldCheck,
  sparkles: Sparkles,
  star: Star,
  sun: Sun,
  "tree-pine": TreePine,
  trophy: Trophy,
  users: Users,
  utensils: Utensils,
  waves: Waves,
};

export const ICON_OPTIONS = Object.keys(iconMap).sort();

export function getIcon(name: string): LucideIcon {
  return iconMap[name] ?? Sparkles;
}